name: Python Dependencies Security Scan

on:
  push:
    branches: ["main"]
    paths:
      - "requirements.txt"
  pull_request:
    branches: ["main"]
    paths:
      - "requirements.txt"
      
jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scanners: "vuln"
          format: "table"
          exit-code: 1
          severity: "CRITICAL,HIGH,MEDIUM"
