name: Python Dependencies Security Scan

on:
  push:
    branches: ["main"]
    
  pull_request:
    branches: ["main"]
      
jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validadte requirements
        run: test -s requirements.txt

      - name: Build Docker Image
        run: docker build -t vuln-python-app:local .

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "vuln-python-app:local"
          format: "table"
          exit-code: 1
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
